version: '3.9'
services:
  dynamodb-local:
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    image: my-dynamodb-local
    build:
      context: ./build
      dockerfile: Dockerfile
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

volumes:
  dynamodb-data:
