name: ci

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test-on-ci:
    # 指定可能なもの一覧 https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    # イメージ詳細 https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
    # イメージにNode.js, yarn, docker, docker-compose, aws cliはあらかじめインストールされている
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: dumy
      AWS_SECRET_ACCESS_KEY: dumy
      AWS_DEFAULT_REGION: local-env

    steps:
      - uses: actions/checkout@v3

      - name: yarn install
        run: yarn install

      - name: dyanamodb execute and create table
        run: |
          docker-compose up -d
          aws dynamodb create-table --cli-input-json file://./commands/create-table-user.json --endpoint-url http://localhost:8000

      - name: run test
        run: yarn test
